# Лабораторна робота №2 
### Оцінювання параметрів статистичної вибірки

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
N = 100

M = 20
MG = 51

In [ ]:
rv = stats.uniform(10 + M, MG + 2 * M)

In [ ]:
population = rv.rvs(size=N)

In [ ]:
sample = np.random.choice(population, M)

### a)

In [ ]:
Y = np.sum(population)

In [ ]:
Ys = Y / N

In [ ]:
DY2 = np.var(population, ddof=1)

In [ ]:
print("Сумма = {}"
      "\nСереднє значення = {}\n"
      "Середньоквадратичне відхилення = {}".format(Y, Ys, DY2))

Сумма = 7259.719175871692
Середнє значення = 72.59719175871692
Середньоквадратичне відхилення = 678.7871208203798


### б)

In [ ]:
Y_ = N * np.sum(sample / M)

In [ ]:
Ys_ = np.sum(sample) / M

In [ ]:
S2 = np.var(sample, ddof=1)

In [ ]:
print("Сумма = {}"
      "\nСереднє значення = {}\n"
      "Середньоквадратичне відхилення = {}".format(Y_, Ys_, S2))

Сумма = 7433.138790677948
Середнє значення = 74.3313879067795
Середньоквадратичне відхилення = 797.0073958306787


In [ ]:
DY_s = (S2 / M) * np.sqrt(1 - M / N)

In [ ]:
DY_ = S2 * N**2 * (1 - M / N)

In [ ]:
average_interval = (
    Ys_ - 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / M, 
    Ys_ + 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / M
)

print("Довірчий інтерва для середнього значення:\n"
      "{}".format(average_interval))

Довірчий інтерва для середнього значення:
(71.07402700273238, 77.58874881082662)


In [ ]:
population_interval = (
    N * Ys_ - 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / np.sqrt(M), 
    N * Ys_ + 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / np.sqrt(M)
)

print("Довірчий інтервал для загальної суми популяції:\n"
      "{}".format(population_interval))

Довірчий інтервал для загальної суми популяції:
(7418.571429860551, 7447.706151495349)


In [ ]:
def selective_research(population, sample, disp=True): 
    # сумма популяції
    Y = np.sum(population)
    
    # розмір популяції
    N = population.shape[0]
    
    # розмір вибірки
    M = sample.shape[0]
    
    # середнє значення популяції
    Ys = Y / N
    DY2 = np.var(population, ddof=1)
    
    Y_ = N * np.sum(sample / M)
    Ys_ = np.sum(sample) / M
    S2 = np.var(sample, ddof=1)
    
    DY_s = (S2 / M) * np.sqrt(1 - M / N)
    DY_ = S2 * N**2 * (1 - M / N)
    
    average_interval = (
        Ys_ - 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / np.sqrt(M), 
        Ys_ + 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / np.sqrt(M)
    )
    
    population_interval = (
        N * Ys_ - 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / np.sqrt(M), 
        N * Ys_ + 2.58 * np.sqrt(S2) * np.sqrt(1 - M / N) / np.sqrt(M)
    )
    
    if disp:
        print("\nПопуляція:"
              "\n\tСумма = {}"
              "\n\tСереднє значення = {}"
              "\n\tСередньоквадратичне відхилення = {}".format(Y, Ys, DY2))
        print("\nВибірка:"
              "\n\tСумма = {}"
              "\n\tСереднє значення = {}"
              "\n\tСередньоквадратичне відхилення = {}".format(Y_, Ys_, S2))
        
        print("\nДовірчий інтерва для середнього значення:"
              "\n\t{}".format(average_interval))
        
        print("\nДовірчий інтервал для загальної суми популяції:"
              "\n\t{}".format(population_interval))
        
    return {
        "average_interval": average_interval,
        "population_interval": population_interval,
        "Y": Y,
        "Ys": Ys,
        "DY2": DY2,
        "Y_": Y_,
        "Ys_": Ys_,
        "S2": S2,
        "DY_s": DY_s,
        "DY_": DY_
    }

In [ ]:
selective_research(population, sample)


Популяція:
	Сумма = 7259.719175871692
	Середнє значення = 72.59719175871692
	Середньоквадратичне відхилення = 678.7871208203798

Вибірка:
	Сумма = 7433.138790677948
	Середнє значення = 74.3313879067795
	Середньоквадратичне відхилення = 797.0073958306787

Довірчий інтерва для середнього значення:
	(59.76402708938045, 88.89874872417855)

Довірчий інтервал для загальної суми популяції:
	(7418.571429860551, 7447.706151495349)


{'DY2': 678.7871208203798,
 'DY_': 6376059.16664543,
 'DY_s': 35.6432543129496,
 'S2': 797.0073958306787,
 'Y': 7259.719175871692,
 'Y_': 7433.138790677948,
 'Ys': 72.59719175871692,
 'Ys_': 74.3313879067795,
 'average_interval': (59.76402708938045, 88.89874872417855),
 'population_interval': (7418.571429860551, 7447.706151495349)}

In [ ]:
population = rv.rvs(size=10000)

In [ ]:
selective_research(population=population, 
                   sample=np.random.choice(population, 100))


Популяція:
	Сумма = 755694.1798678852
	Середнє значення = 75.56941798678852
	Середньоквадратичне відхилення = 694.4006064448641

Вибірка:
	Сумма = 751793.249538928
	Середнє значення = 75.1793249538928
	Середньоквадратичне відхилення = 648.8515445198054

Довірчий інтерва для середнього значення:
	(68.640345471793, 81.71830443599261)

Довірчий інтервал для загальної суми популяції:
	(751786.7105594459, 751799.7885184102)


{'DY2': 694.4006064448641,
 'DY_': 64236302907.46074,
 'DY_s': 6.455991353444331,
 'S2': 648.8515445198054,
 'Y': 755694.1798678852,
 'Y_': 751793.249538928,
 'Ys': 75.56941798678852,
 'Ys_': 75.1793249538928,
 'average_interval': (68.640345471793, 81.71830443599261),
 'population_interval': (751786.7105594459, 751799.7885184102)}

In [ ]:
selective_research(population=population, 
                   sample=np.random.choice(population, 1000))


Популяція:
	Сумма = 755694.1798678852
	Середнє значення = 75.56941798678852
	Середньоквадратичне відхилення = 694.4006064448641

Вибірка:
	Сумма = 750332.6032886156
	Середнє значення = 75.03326032886156
	Середньоквадратичне відхилення = 701.5820053501147

Довірчий інтерва для середнього значення:
	(72.98313608521893, 77.08338457250419)

Довірчий інтервал для загальної суми популяції:
	(750330.553164372, 750334.6534128592)


{'DY2': 694.4006064448641,
 'DY_': 63142380481.51033,
 'DY_s': 0.66557913068844,
 'S2': 701.5820053501147,
 'Y': 755694.1798678852,
 'Y_': 750332.6032886156,
 'Ys': 75.56941798678852,
 'Ys_': 75.03326032886156,
 'average_interval': (72.98313608521893, 77.08338457250419),
 'population_interval': (750330.553164372, 750334.6534128592)}

In [ ]:
sample100 = []
sample1000 = []

for i in range(population.shape[0]):
    if i % 100 == 0:
        sample100.append(population[i])
    if i % 10 == 0:
        sample1000.append(population[i])
        
sample100 = np.array(sample100)
sample1000 = np.array(sample1000)

In [ ]:
selective_research(population=population, 
                   sample=sample100)


Популяція:
	Сумма = 755694.1798678852
	Середнє значення = 75.56941798678852
	Середньоквадратичне відхилення = 694.4006064448641

Вибірка:
	Сумма = 714534.2142525075
	Середнє значення = 71.45342142525075
	Середньоквадратичне відхилення = 703.1684545611356

Довірчий інтерва для середнього значення:
	(64.64624521485973, 78.26059763564177)

Довірчий інтервал для загальної суми популяції:
	(714527.4070762972, 714541.0214287179)


{'DY2': 694.4006064448641,
 'DY_': 69613677001.55241,
 'DY_s': 6.996437784580071,
 'S2': 703.1684545611356,
 'Y': 755694.1798678852,
 'Y_': 714534.2142525075,
 'Ys': 75.56941798678852,
 'Ys_': 71.45342142525075,
 'average_interval': (64.64624521485973, 78.26059763564177),
 'population_interval': (714527.4070762972, 714541.0214287179)}

In [ ]:
selective_research(population=population, sample=sample1000)


Популяція:
	Сумма = 755694.1798678852
	Середнє значення = 75.56941798678852
	Середньоквадратичне відхилення = 694.4006064448641

Вибірка:
	Сумма = 761174.5696272865
	Середнє значення = 76.11745696272864
	Середньоквадратичне відхилення = 725.5901158538811

Довірчий інтерва для середнього значення:
	(74.03255019204252, 78.20236373341476)

Довірчий інтервал для загальної суми популяції:
	(761172.4847205157, 761176.6545340571)


{'DY2': 694.4006064448641,
 'DY_': 65303110426.8493,
 'DY_s': 0.6883552241411143,
 'S2': 725.5901158538811,
 'Y': 755694.1798678852,
 'Y_': 761174.5696272865,
 'Ys': 75.56941798678852,
 'Ys_': 76.11745696272864,
 'average_interval': (74.03255019204252, 78.20236373341476),
 'population_interval': (761172.4847205157, 761176.6545340571)}

In [ ]:
size_of_population = population.shape[0]
proportions = [0.5, 0.3, 0.2]

stratified_population = np.array([
    population[: int(proportions[0] * size_of_population)],
    
    population[int(proportions[0] * size_of_population): 
               int((proportions[0] + proportions[1]) * size_of_population)],
    
    population[int((proportions[0] + proportions[1]) * size_of_population):]
])

In [ ]:
size_of_sample = 1000

In [ ]:
sample = np.array([
    np.random.choice(stratified_population[0], int(size_of_sample * proportions[0])),
    np.random.choice(stratified_population[1], int(size_of_sample * proportions[1])),
    np.random.choice(stratified_population[2], int(size_of_sample * proportions[2]))
])

In [ ]:
joined_sample = np.array([])
joined_sample = np.append(joined_sample, sample[0])
joined_sample = np.append(joined_sample, sample[1])
joined_sample = np.append(joined_sample, sample[2])

In [ ]:
selective_research(population=population, sample=joined_sample)


Популяція:
	Сумма = 755694.1798678852
	Середнє значення = 75.56941798678852
	Середньоквадратичне відхилення = 694.4006064448641

Вибірка:
	Сумма = 759742.3345031086
	Середнє значення = 75.97423345031086
	Середньоквадратичне відхилення = 681.2828056234728

Довірчий інтерва для середнього значення:
	(73.95398550002929, 77.99448140059243)

Довірчий інтервал для загальної суми популяції:
	(759740.3142551583, 759744.354751059)


{'DY2': 694.4006064448641,
 'DY_': 61315452506.11255,
 'DY_s': 0.6463216189439832,
 'S2': 681.2828056234728,
 'Y': 755694.1798678852,
 'Y_': 759742.3345031086,
 'Ys': 75.56941798678852,
 'Ys_': 75.97423345031086,
 'average_interval': (73.95398550002929, 77.99448140059243),
 'population_interval': (759740.3142551583, 759744.354751059)}

In [ ]:
n = size_of_sample
N = size_of_population

nh = np.array([
    sample[0].shape[0],
    sample[1].shape[0],
    sample[2].shape[0]
])

Nh = np.array([
    stratified_population[0].shape[0],
    stratified_population[1].shape[0],
    stratified_population[2].shape[0]
])

# вибіркова вага
wh = np.array([
    Nh[0] / nh[0], 
    Nh[1] / nh[1],
    Nh[2] / nh[2]
])

# середнє значення для страти h
y_h = np.array([
    np.mean(stratified_population[0]), 
    np.mean(stratified_population[1]), 
    np.mean(stratified_population[2])
])

# загальна сума для страти h
Yh = np.array([
    np.sum(stratified_population[0]), 
    np.sum(stratified_population[1]), 
    np.sum(stratified_population[2])
])

# загальна сума для всієї популяції
Y = np.sum(Yh)

# середнє значення для всієї популяції
y_U = Y / N

# дисперсія в страті h
S2h = np.array([
    np.var(stratified_population[0], ddof=1),
    np.var(stratified_population[1], ddof=1),
    np.var(stratified_population[2], ddof=1)
])

print("\nВибіркова вага:\n\t{}"
      "\nCереднє значення для страти h:\n\t{}"
      "\nЗагальна сума для страти h:\n\t{}"
      "\nЗагальна сума для всієї популяції:\n\t{}"
      "\nСереднє значення для всієї популяції:\n\t{}"
      "\nДисперсія в страті h:\n\t{}".format(wh, y_h, Yh, Y, y_U, S2h))


Вибіркова вага:
	[10. 10. 10.]
Cереднє значення для страти h:
	[75.47949177 75.74966636 75.52386097]
Загальна сума для страти h:
	[377397.45883056 227248.99909077 151047.72194656]
Загальна сума для всієї популяції:
	755694.1798678851
Середнє значення для всієї популяції:
	75.56941798678851
Дисперсія в страті h:
	[697.2348245  680.15887175 709.30278483]


In [ ]:
# вага страти h
Wh = Nh / N

# оцінка середнього для страти h, h=1,...,N
y_h_ = np.array([
    np.mean(sample[0]), 
    np.mean(sample[1]), 
    np.mean(sample[2])
])

# оцінка загальної суми для страти h, h=1,...,N
Yh_ = y_h_ * Nh

# оцінка вибіркової дисперсії для страти h, h=1,...,N
s2h = np.array([
    np.var(sample[0], ddof=1),
    np.var(sample[1], ddof=1),
    np.var(sample[2], ddof=1)
])

print("\nВага страти h:\n\t{}"
      "\nОцінка середнього для страти h:\n\t{}"
      "\nОцінка загальної суми для страти h:\n\t{}"
      "\nОцінка вибіркової дисперсії для страти h:\n\t{}".format(Wh, y_h_, Yh_, s2h))


Вага страти h:
	[0.5 0.3 0.2]
Оцінка середнього для страти h:
	[77.16895655 75.17998333 74.17880089]
Оцінка загальної суми для страти h:
	[385844.78274355 225539.94998363 148357.60177592]
Оцінка вибіркової дисперсії для страти h:
	[684.66094445 653.2784914  713.95877072]


In [ ]:
Y_st = np.sum(Nh * y_h_)
y_st = np.sum(Wh * y_h_)

print("\nОцінка суми популяції:\n\t{}"
      "\nОцінка середнього популяції:\n\t{}".format(Y_st, y_st))


Оцінка суми популяції:
	759742.3345031086
Оцінка середнього популяції:
	75.97423345031086


In [ ]:
DY_st = np.sum((1 - nh/Nh) * Nh **2 * s2h / nh)
Dy_st = DY_st / (N ** 2)

print("\nНезміщена оцінка дисперсії:"
      "\n\t{}"
      "\n\t{}".format(DY_st, Dy_st))


Незміщена оцінка дисперсії:
	61299519.64102872
	0.6129951964102872


In [ ]:
print("Довірчий інтервал для оцінки середнього значення:")
print((y_st - 2.58 * np.sqrt(Dy_st), y_st + 2.58 * np.sqrt(Dy_st)))

Довірчий інтервал для оцінки середнього значення:
(73.95424799853517, 77.99421890208656)


In [ ]:
# Дисперсійний аналіз: Кобзар Прикладна математична статистика
# Бахрушин: Методу аналізу даних
# Мостицький: Статистичний аналіз в R

In [7]:
a = "{0:15}".format("lol")

In [21]:
a = "{0:14}".format(1)

In [22]:
a

'             1'